### ISSUE TITLE
Doesn't accept Integer value.

### ISSUE THREAD

**Issue by papakay** [dreambo8563/vue-circular-progress#14]
Hello, I really commend the great work done on this library.

I tried using in one of my projects but I'm having issue with passing integer value. I get a `Maximum call stack size exceeded` error.

Please what can be done to resolve this issue?

Thank you.

**Comment by dreambo8563** [comment]
I will look into that, could you please describe your scenario, you do want to show the number like 7.0 or just 7?

**Comment by dreambo8563** [comment]
1.0.3 published.

you can see the decimal part and the decimal dot has a class name, you can override the class to hide them if you want. thanks for your issue

**Comment by dreambo8563** [comment]
@papakay if this lib helped, please give me a star, thanks 😁

**Comment by papakay** [comment]
@dreambo8563 , thanks for your prompt update. I've given you a star. You did a great job!
