### ISSUE TITLE
Please can you add the ability to set the label

### ISSUE THREAD

**Issue by ghost** [dreambo8563/vue-circular-progress#16]
It'd be nice to have the ability to set the text inside the circle to something other than the percentage - could you add this as a feature?

**Comment by dreambo8563** [comment]
I will look into that later

**Comment by dreambo8563** [comment]
I consider to use the default slot for this requirement and ignore the countdown effect if default slot exist.

**Comment by Human626** [comment]
Thank you, I look forward to hearing back about it soon.

**Comment by ghost** [comment]
Sounds good. So long as I can set the label to be a text field instead of displaying the value.

**Comment by dreambo8563** [comment]
@Human626 1.0.4 published,  doc and demo updated, have a try.  😁

**Comment by ghost** [comment]
Perfect! Thank you!! 😄
