### ISSUE TITLE
Please update Readme to explain how to use this component

### ISSUE THREAD

**Issue by CodeNameNinja** [dreambo8563/vue-circular-progress#32]
I am trying to follow the Readme, but the example imports Progess from index.vue? and then of course this will throw 'Cannot find index.vue' what is Index.vue? how does one actually use this component

**Comment by rizkhal** [comment]
I was also wondering about this

Then i tried to import from "easy-circular-progress" and it working perfectly

**Comment by dfourcfive** [comment]
@rizkhal 
i used  this:
-import progress from "../../node_modules/easy-circular-progress/src/index.vue";
-import progress from "./index.vue"
And also this "./easy-circular-progress"
and didn't work for me  (This relative module was not found)
can you show us how you did it?
i'm using gridsome

**Comment by dreambo8563** [comment]
I will update readme  later
